# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0003_auto_20170309_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='id',
        ),
        migrations.AddField(
            model_name='username',
            name='user_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
