# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0004_auto_20170309_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(blank=True, choices=[(None, None), ('VT', 'Vegetarian'), ('VG', 'Vegan'), ('HL', 'Halal'), ('KS', 'Kosher'), ('GF', 'Gluten-Free')], max_length=500)),
                ('distance', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('hurry', models.BooleanField()),
                ('arrival_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pandora.Username')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='address_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dietrestrictions',
            name='choices',
            field=models.CharField(blank=True, choices=[('VT', 'Vegetarian'), ('VG', 'Vegan'), ('HL', 'Halal'), ('KS', 'Kosher'), ('GF', 'Gluten-Free')], max_length=500),
        ),
        migrations.AlterField(
            model_name='distance',
            name='distance_integer',
            field=models.IntegerField(blank=True),
        ),
    ]
