# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0005_auto_20170311_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 11, 17, 8, 43, 316980)),
        ),
    ]
