# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0005_auto_20170309_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResponsesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query1', models.CharField(max_length=100)),
                ('search_query2', models.CharField(max_length=100)),
                ('search_query3', models.CharField(max_length=100)),
                ('search_query4', models.CharField(max_length=100)),
                ('search_query5', models.CharField(max_length=100)),
            ],
        ),
    ]
