# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0006_searchresponsesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsesmodel',
            name='arrival_time',
        ),
        migrations.AddField(
            model_name='responsesmodel',
            name='arrival_day',
            field=models.CharField(blank=True, choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='username',
            name='username',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
