# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0007_auto_20170310_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesmodel',
            name='diet',
            field=models.CharField(blank=True, choices=[('VT', 'Vegetarian'), ('VG', 'Vegan'), ('HL', 'Halal'), ('KS', 'Kosher'), ('GF', 'Gluten-Free')], max_length=500),
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='hurry',
            field=models.NullBooleanField(),
        ),
    ]
