# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 04:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0008_auto_20170313_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 13, 23, 18, 32, 587751)),
        ),
    ]
