# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0008_auto_20170310_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
