# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 06:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0009_auto_20170313_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickrestaurantsmodel',
            old_name='pick_results1',
            new_name='pick_results',
        ),
        migrations.RenameField(
            model_name='pickrestaurantsmodel',
            old_name='rating1',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='searchrestaurantsmodel',
            old_name='search_query1',
            new_name='search_query',
        ),
        migrations.RemoveField(
            model_name='pickrestaurantsmodel',
            name='pick_results2',
        ),
        migrations.RemoveField(
            model_name='pickrestaurantsmodel',
            name='pick_results3',
        ),
        migrations.RemoveField(
            model_name='pickrestaurantsmodel',
            name='pick_results4',
        ),
        migrations.RemoveField(
            model_name='pickrestaurantsmodel',
            name='pick_results5',
        ),
        migrations.RemoveField(
            model_name='pickrestaurantsmodel',
            name='rating2',
        ),
        migrations.RemoveField(
            model_name='pickrestaurantsmodel',
            name='rating3',
        ),
        migrations.RemoveField(
            model_name='pickrestaurantsmodel',
            name='rating4',
        ),
        migrations.RemoveField(
            model_name='pickrestaurantsmodel',
            name='rating5',
        ),
        migrations.RemoveField(
            model_name='searchrestaurantsmodel',
            name='search_query2',
        ),
        migrations.RemoveField(
            model_name='searchrestaurantsmodel',
            name='search_query3',
        ),
        migrations.RemoveField(
            model_name='searchrestaurantsmodel',
            name='search_query4',
        ),
        migrations.RemoveField(
            model_name='searchrestaurantsmodel',
            name='search_query5',
        ),
        migrations.AddField(
            model_name='pickrestaurantsmodel',
            name='search_again',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)], default=False),
        ),
        migrations.AlterField(
            model_name='pickrestaurantsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.Username'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='accept',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)], default=True),
        ),
        migrations.AlterField(
            model_name='rejectionmodel',
            name='cuisine',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)], default=False),
        ),
        migrations.AlterField(
            model_name='rejectionmodel',
            name='price_high',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)], default=False),
        ),
        migrations.AlterField(
            model_name='rejectionmodel',
            name='price_low',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)], default=False),
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 14, 1, 33, 48, 146850)),
        ),
        migrations.AlterField(
            model_name='searchrestaurantsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.Username'),
        ),
    ]
