# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0009_responsesmodel_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsesmodel',
            name='arrival_time',
        ),
    ]
