# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0010_remove_responsesmodel_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 10, 9, 12, 8, 89130)),
        ),
    ]
