# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0011_auto_20170314_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchChoicesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('search_query_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.SearchRestaurantsModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.Username')),
            ],
        ),
        migrations.RemoveField(
            model_name='pickrestaurantsmodel',
            name='pick_results',
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 14, 2, 53, 20, 487020)),
        ),
        migrations.AddField(
            model_name='pickrestaurantsmodel',
            name='search_choices',
            field=models.ManyToManyField(to='pandora.SearchChoicesModel'),
        ),
    ]
