# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0011_responsesmodel_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dietrestrictions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hurry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='time',
            name='user',
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 10, 11, 42, 33, 553212)),
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='distance',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='DietRestrictions',
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
        migrations.DeleteModel(
            name='Hurry',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
