# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0012_auto_20170314_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickrestaurantsmodel',
            name='pick_result',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='pickrestaurantsmodel',
            name='search_again',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='accept',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='rejectionmodel',
            name='cuisine',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='rejectionmodel',
            name='price_high',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='rejectionmodel',
            name='price_low',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 14, 3, 44, 50, 462668)),
        ),
    ]
