# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0012_auto_20170310_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickRestaurantsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_results1', models.CharField(blank=True, max_length=500)),
                ('pick_results2', models.CharField(blank=True, max_length=500)),
                ('pick_results3', models.CharField(blank=True, max_length=500)),
                ('pick_results4', models.CharField(blank=True, max_length=500)),
                ('pick_results5', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RejectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.NullBooleanField()),
                ('price_high', models.NullBooleanField()),
                ('price_low', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchRestaurantsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query1', models.CharField(max_length=100)),
                ('search_query2', models.CharField(blank=True, max_length=100)),
                ('search_query3', models.CharField(blank=True, max_length=100)),
                ('search_query4', models.CharField(blank=True, max_length=100)),
                ('search_query5', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchResponsesModel',
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 10, 14, 8, 36, 283920)),
        ),
    ]
