# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0013_auto_20170310_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickrestaurantsmodel',
            name='pick_results1',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=500),
        ),
        migrations.AlterField(
            model_name='pickrestaurantsmodel',
            name='pick_results2',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=500),
        ),
        migrations.AlterField(
            model_name='pickrestaurantsmodel',
            name='pick_results3',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=500),
        ),
        migrations.AlterField(
            model_name='pickrestaurantsmodel',
            name='pick_results4',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=500),
        ),
        migrations.AlterField(
            model_name='pickrestaurantsmodel',
            name='pick_results5',
            field=models.CharField(blank=True, choices=[(None, None)], max_length=500),
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 10, 14, 28, 15, 101973)),
        ),
    ]
