# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0013_auto_20170314_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickrestaurantsmodel',
            name='pick_result',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 14, 4, 19, 8, 65698)),
        ),
    ]
