# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0014_auto_20170314_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickrestaurantsmodel',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=1),
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 14, 12, 16, 16, 128633)),
        ),
    ]
