# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0017_auto_20170314_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesmodel',
            name='environment',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='responsesmodel',
            name='service',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='responsesmodel',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 3, 14, 13, 41, 41, 880897)),
        ),
    ]
